# Generated by Django 4.0.2 on 2022-03-01 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_orderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='image_url',
            field=models.URLField(blank=True, max_length=250),
        ),
    ]
